name = "Rump"
uuid = "961f73fb-345b-40bd-b0bb-12c52a994620"
authors = ["Carsten Dietzel", "Lukas Gutbrunner", "Silvia Properzi", "Leandro Vendramin"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
