name = "Rump"
uuid = "961f73fb-345b-40bd-b0bb-12c52a994620"
authors = ["Carsten Dietzel", "Lukas Gutbrunner", "Silvia Properzi", "Leandro Vendramin"]
version = "1.0.0-DEV"

[deps]
Combinatorics = "861a8166-3701-5b0c-9a16-15d98fcdc6aa"
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"
Permutations = "2ae35dd2-176d-5d53-8349-f30d82d94d4f"

[compat]
Combinatorics = "1.0.2"
Documenter = "0.27.0, 1"
IterTools = "1.4.0"
Permutations = "0.4.22"
julia = "1.11"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
