name = "Rump"
uuid = "961f73fb-345b-40bd-b0bb-12c52a994620"
authors = ["Carsten Dietzel", "Lukas Gutbrunner", "Silvia Properzi", "Leandro Vendramin"]
version = "1.0.0-DEV"

[deps]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
IterTools = "c8e1da08-722c-5040-9ed9-7db0dc04731e"

[compat]
IterTools = "1.10.0"
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
